### PR TITLE
Repronim

### PR DESCRIPTION
**Pull request by akeshavan**
I really didn't mean to change so many files, my code editor did this craziness. The main thing I added was:

``` javascript  
 "ui": {
        "order": [
            "phq9_1",
            "phq9_2",
            "phq9_3",
            "phq9_4",
            "phq9_5",
            "phq9_6",
            "phq9_7",
            "phq9_8",
            "phq9_9",
            "phq9_10"
        ],
        "shuffle": false,
        "visibility": {
            "phq9_1": true,
            "phq9_2": true,
            "phq9_3": true,
            "phq9_4": true,
            "phq9_5": true,
            "phq9_6": true,
            "phq9_7": true,
            "phq9_8": true,
            "phq9_9": true,
            "phq9_10": "phq9_1 > 0 ||  phq9_2 > 0 || phq9_3 > 0 || phq9_4 > 0 || phq9_5 > 0 || phq9_6 > 0 || phq9_7 > 0 || phq9_8 > 0 || phq9_9 > 0"
        }
```

in PHQ-9:
https://github.com/akeshavan/schema-standardization/blob/master/activities/PHQ-9/phq9_schema.jsonld

And to see it work in UI:  https://schema-ui.anisha.pizza/#/activities/1?url=https%3A%2F%2Fraw.githubusercontent.com%2Fakeshavan%2Fschema-standardization%2Fmaster%2Factivity-sets%2Fexample%2Fnda-phq.jsonld

### CODE REVIEW

**Comment by sanuann** [comment]
is the "visibility" key for branching?

**Comment by akeshavan** [comment]
yep

**Comment by sanuann** [comment]
then why not remove the "branchingLogic"? and the "hidden" key at item level?

**Comment by akeshavan** [comment]
sure, i left it in case there were any strong opinions on why it should be there

**Pull request merged**
